version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001" # Maps localhost:3001 to the container
    env_file:
      - ./backend/.env # Loads your Aiven DATABASE_URL and Resend/Gmail keys safely
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./Planet.X_Vite
    ports:
      - "5173:5173" # Maps localhost:5173 to the container
    volumes:
      - ./Planet.X_Vite:/app
      - /app/node_modules
    depends_on:
      - backend